# --- Configurações do Cluster (Baseado no seu sinfo) ---
PARTITION=l40s         # Partição padrão (conforme seu sinfo)
GPUS=1                 # Quantidade de GPUs
CPUS=4                 
MEM=16G                
TIME=02:00:00          

# Dica: Para usar a rtx8000, mude PARTITION=rtx8000 no arquivo